#!/bin/bash

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then

  # show Library folder
  chflags nohidden ~/Library

  # show hidden files
  defaults write com.apple.finder AppleShowAllFiles YES

  # show path bar
  defaults write com.apple.finder ShowPathbar -bool true

  # show status bar
  defaults write com.apple.finder ShowStatusBar -bool true

  # set locale (ends up with en_NO.UTF-8 otherwise when language set to english and region is Norway)
  defaults write NSGlobalDomain AppleLocale en_US

  source $HOME/.config/yadm/bootstrap-homebrew
  source $HOME/.config/yadm/bootstrap-iterm2
  source $HOME/.config/yadm/bootstrap-pyenv

  # install neovim gem
  gem install --user-install neovim

  # change to fish shell
  FISH_LOCATION=$(which fish)
  if [ -f "$FISH_LOCATION" ]; then
    if grep -Fxq "$FISH_LOCATION" /etc/shells; then
      echo fish already setup as allowed shell
    else
      echo adding $FISH_LOCATION as allowed shell
      sudo sh -c "echo $FISH_LOCATION >> /etc/shells"
      chsh -s $FISH_LOCATION
    fi
  fi
fi
