#!/bin/bash

source $HOME/.config/yadm/bootstrap-repo
source $HOME/.config/yadm/bootstrap-global-npm-packages
source $HOME/.config/yadm/bootstrap-mac
source $HOME/.config/yadm/bootstrap-vim
source $HOME/.config/yadm/bootstrap-fish
