#!/bin/bash

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then

  # show Library folder
  chflags nohidden ~/Library

  # show hidden files
  defaults write com.apple.finder AppleShowAllFiles YES

  # show path bar
  defaults write com.apple.finder ShowPathbar -bool true

  # show status bar
  defaults write com.apple.finder ShowStatusBar -bool true

  # set locale (ends up with en_NO.UTF-8 otherwise when language set to english and region is Norway)
  defaults write NSGlobalDomain AppleLocale en_US

  source $HOME/.config/yadm/bootstrap-homebrew
  source $HOME/.config/yadm/bootstrap-iterm2
  source $HOME/.config/yadm/bootstrap-pyenv

  # install neovim gem
  gem install --user-install neovim

  # change to fish shell
  if [ -f "/usr/local/bin/fish" ]; then
    if grep -Fxq "/usr/local/bin/fish" /etc/shells; then
      echo fish already setup as allowed shell
    else
      echo adding /usr/local/bin/fish as allowed shell
      sudo sh -c "echo /usr/local/bin/fish >> /etc/shells"
      chsh -s /usr/local/bin/fish
    fi
  fi
fi
