#!/bin/bash

pyenv install -s 2.7.14 && pyenv virtualenv 2.7.14 neovim2 && pyenv activate neovim2 && pip install neovim
pyenv install -s 3.6.2 && pyenv virtualenv 3.6.2 neovim3 && pyenv activate neovim3 && pip install neovim
