#!/bin/bash

if command -v nvim >/dev/null 2>&1; then
  echo adding javascript-typescript-langserver
  yarn global add javascript-typescript-langserver
  echo bootstrap neovim
  nvim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
fi


